name: keep render awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: send request
        run: |
          curl -X GET https://havamana-server.onrender.com/health \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"